import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { 
  JournalVoucherEntryComponent,
  JournalVoucherListComponent,
  DebitPaymentVoucherEntryComponent, 
  DebitPaymentVoucherListComponent,
  BusinessCofigComponent,
  CoaComponent,
  SubLedgerComponent,
  CreditReceiptVoucherEntryComponent,
  CreditReceiptVoucherListComponent,
  ProjectComponent,
  FinancialYearComponent,
  OrgWiseCoaComponent,
  FinancialYearCloseComponent,
  LockVoucherEditOrEntryComponent,
  FixedIDs,
  OpeningBalanceComponent,
  ContraVoucherEntryComponent,
  ContraVoucherListComponent,
  OpeningBalanceListComponent,
  VoucherApprovalComponent,
  VoucherApprovalPendingComponent,
  ChartOfAccountsReportComponent,
  ReceiptsAndPaymentsComponent,
  TrialBalanceComponent,
  DayBookComponent,
  GroupLedgerRptComponent,
  BalanceSheetComponent,
  BankBookComponent,
  CashBookComponent,
  LedgerRptComponent,
  IncomeStatementComponent,
  SubLedgerRptComponent,
  NoteLedgerComponent,
  SubLedgerDetailsComponent,
  FixedAssetsScheduleComponent,
  ChequeBookComponent,
  ChequeBookLeafManagementComponent,
  ChequeLogComponent,
  ReceivedChequeManagementComponent
} from './index';



const routes: Routes = [
  { path: 'journal-voucher-entry', component: JournalVoucherEntryComponent},
  { path: 'journal-voucher-list', component: JournalVoucherListComponent},
  { path: 'debit-payment-voucher-entry', component: DebitPaymentVoucherEntryComponent},
  { path: 'debit-payment-voucher-list', component: DebitPaymentVoucherListComponent},
  { path: 'business-config-accounting', component: BusinessCofigComponent},
  { path: 'coa', component: CoaComponent},
  { path: 'financial-year', component: FinancialYearComponent},
  { path: 'credit-receipt-voucher-entry', component: CreditReceiptVoucherEntryComponent},
  { path: 'credit-receipt-voucher-list', component: CreditReceiptVoucherListComponent},
  { path: 'project-information', component: ProjectComponent},
  { path: 'org-wise-coa', component: OrgWiseCoaComponent},
  { path: 'financial-year-close', component: FinancialYearCloseComponent},
  { path: 'lock-voucher-edit-or-entry', component: LockVoucherEditOrEntryComponent},
  { path: 'project-wise-coa', component: OrgWiseCoaComponent,data: { projectWise: FixedIDs.coaType.ProjectWise }},
  { path: 'sub-ledger', component: SubLedgerComponent},
  { path: 'opening-balance', component: OpeningBalanceComponent},
  { path: 'contra-voucher-entry', component: ContraVoucherEntryComponent},
  { path: 'contra-voucher-list', component: ContraVoucherListComponent},
  { path: 'opening-balance-list', component: OpeningBalanceListComponent},
  { path: 'voucher-approval-list', component: VoucherApprovalComponent},
  { path: 'voucher-approval-pending-list', component: VoucherApprovalPendingComponent},
  { path: 'chart-of-accounts-report', component: ChartOfAccountsReportComponent},
  { path: 'receipts-and-payments', component: ReceiptsAndPaymentsComponent},
  { path: 'trial-balance', component: TrialBalanceComponent},
  { path: 'day-book', component: DayBookComponent},
  { path: 'group-ledger', component: GroupLedgerRptComponent},
  { path: 'balance-sheet', component: BalanceSheetComponent},
  { path: 'bank-book', component: BankBookComponent},
  { path: 'cash-book', component: CashBookComponent},
  { path: 'ledger', component: LedgerRptComponent},
  { path: 'income-statement', component: IncomeStatementComponent},
  { path: 'sub-ledger-rpt', component: SubLedgerRptComponent},
  { path: 'note-ledger', component: NoteLedgerComponent},
  { path: 'sub-ledger-details', component: SubLedgerDetailsComponent},
  { path: 'fixed-assets-schedule', component: FixedAssetsScheduleComponent},
  { path: 'cheque-book', component: ChequeBookComponent},
  { path: 'cheque-book-leaf-management', component: ChequeBookLeafManagementComponent},
  { path: 'cheque-log', component: ChequeLogComponent},
  { path: 'received-cheque-management', component: ReceivedChequeManagementComponent},
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class AccountingRoutingModule { }
